@extends('layouts.app')

@section('content')
<section class="terms-section-wrap">
    <div class="terms-section-inner white ">
        <div class="form-section">
            <h1>Terms of Services</h1>
        </div>
        <div class="terms-content">
            <div class="terms-section-content">
                <p>Last updated: October 06, 2021</p>
                <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of
                    Your information when You use the Service and tells You about Your privacy rights and how the law
                    protects You.</p>
                <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the
                    collection and use of information in accordance with this Privacy Policy. This Privacy Policy has
                    been created with the help of the Privacy Policy Generator.</p>
                <h3>Interpretation and Definitions</h3>
                <br>
                <h4>Interpretation</h4>
                <p>The words of which the initial letter is capitalized have meanings defined under the following
                    conditions. The following definitions shall have the same meaning regardless of whether they appear
                    in singular or in plural.</p>
                <br>
                <h4>Definitions</h4>
                <ul>
                    <li>Account means a unique account created for You to access our Service or parts of our Service.
                    </li>
                    <li>Affiliate means an entity that controls, is controlled by or is under common control with a
                        party, where "control" means ownership of 50% or more of the shares, equity interest or other
                        securities entitled to vote for election of directors or other managing authority.
                    </li>
                    <li>Application means the software program provided by the Company downloaded by You on any
                        electronic device, named Lucia
                    </li>
                    <li>Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to
                        My Tripkit LLC, 58 arbor field way, lake grove, ny 11755 US.</li>
                    <li>Cookies are small files that are placed on Your computer, mobile device or any other device by a
                        website, containing the details of Your browsing history on that website among its many uses.
                    </li>
                    <li>Country refers to: New York, United States</li>
                    <li>Device means any device that can access the Service such as a computer, a cellphone or a digital
                        tablet.</li>
                    <li>Personal Data is any information that relates to an identified or identifiable individual.</li>
                    <li>Service refers to the Application or the Website or both.</li>
                    <li>Service Provider means any natural or legal person who processes the data on behalf of the
                        Company. It refers to third-party companies or individuals employed by the Company to facilitate
                        the Service, to provide the Service on behalf of the Company, to perform services related to the
                        Service or to assist the Company in analyzing how the Service is used.</li>
                    <li>Usage Data refers to data collected automatically, either generated by the use of the Service or
                        from the Service infrastructure itself (for example, the duration of a page visit).</li>
                    <li>Website refers to Lucia, accessible from www.letslucia.com</li>
                    <li>You means the individual accessing or using the Service, or the company, or other legal entity
                        on behalf of which such individual is accessing or using the Service, as applicable.</li>
                </ul>
                <div class="form-section termsServiceForm">
                    <form method="POST" action="{{ route('register') }}" id="termsServiceForm">
                        @csrf
                        <input type="checkbox" name="agreement" value="1"> <b>I agree to these Terms and
                            Conditions.</b>
                        <ul class="term-submit-btn-wrapper">
                            <li class="submit-btns next-step">
                                <input type="submit" name="next-step" value="Submit">
                            </li>
                        </ul>
                    </form>
                </div>

            </div>
        </div>
    </div>
</section>
@endsection
@push('js')
<script src="{{ asset('assets/js/jquery.validate.min.js') }}"></script>
<script src="{{ asset('assets/js/additional-methods.min.js') }}"></script>

<script>
jQuery(document).ready(function($) {
    if ($("#termsServiceForm").length > 0) {

        $("#termsServiceForm").validate({
            rules: {
                agreement: {
                    required: true,
                },
            },
            messages: {
                agreement: {
                    required: "Please accept terms and conditions.",
                },
            },
            highlight: function(element, errorClass) {
                $(element).removeClass(errorClass); //prevent class to be added to selects
            },
            errorPlacement: function(error, element) {
                if (element.attr("name") == "agreement") {
                    error.insertAfter("b");

                } else {
                    error.insertAfter(element);
                }
            },
            submitHandler: function(form) {
                form.submit();
            }
        })
    }

});
</script>
@endpush